language: node_js
node_js:
    - 0.10

branches:
    only:
        - master

install:
    - npm install -g grunt-cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install

script:
    - grunt travis
