language: node_js
node_js:
- '0.10'
- '0.11'
env:
  global:
  - secure: Y9cyzdN7Pidsl/6VK3a57xDjdf/JVPuvtl2GZboH3jFbH1LqQdyaCAq6i23yD5zbHhQ486rPagpsCjdxVu4OMwMnt4d8W7na6tqJ982HHtzL/cCSNtVI4qeFXWZ6bc1gFe3mchEEzFk20eBlqcoCaChlq7wadG1EwNC2T6/s9oM=
install:
- npm install grunt-cli coveralls
- npm install
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- ./node_modules/.bin/grunt
- cat ./build/coverage/**/lcov.info | ./node_modules/.bin/coveralls
